from typing import Protocol, Self

from .actor import Actor


class ComponentProtocol(Protocol):
    def register[T: Actor](self, actor: T) -> tuple[Self, T]: ...
    def pre_time_step[T: Actor](self, actor: T) -> tuple[Self, T]: ...
    def pre_optim_iter[T: Actor](self, actor: T) -> tuple[Self, T]: ...
