#:schema https://json.schemastore.org/ruff.json
extend = ".config/linters/.ruff.toml"
extend-exclude = ["marimo/*.py"]
target-version = "py312"

[lint]
extend-ignore = ["F722", "N802", "N803", "N806", "N815"]
