# -*- mode: toml; -*-
# :schema https://json.schemastore.org/pyproject.json
# ref: <https://packaging.python.org/en/latest/specifications/pyproject-toml/>

[build-system]
build-backend = "hatchling.build"
requires = ["hatch-vcs", "hatchling"]

[dependency-groups]
build = ["check-wheel-contents", "hatch", "twine"]
dev = ["icecream"]
docs = [
  "gitpython",
  "mdx-truly-sane-lists",
  "mike",
  "mkdocs",
  "mkdocs-autorefs",
  "mkdocs-gen-files",
  "mkdocs-git-committers-plugin-2",
  "mkdocs-git-revision-date-localized-plugin",
  "mkdocs-include-markdown-plugin",
  "mkdocs-literate-nav",
  "mkdocs-material[imaging]",
  "mkdocs-section-index",
  "mkdocstrings",
  "mkdocstrings-python",
  "pymdown-extensions",
  "ruff",
]
test = [
  "pytest",
  "pytest-benchmark",
  "pytest-codspeed",
  "pytest-cov",
  "pytest-xdist",
]

[project]
authors = [
  { email = "30631553+liblaf@users.noreply.github.com", name = "liblaf" },
]
classifiers = [
  # common classifiers
  # ref: <https://pypi.org/classifiers/>
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "License :: OSI Approved",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python",
  "Typing :: Typed",
]
dependencies = [
  "beartype>=0.20.2,<0.21",
  "einops>=0.8.1,<0.9",
  "felupe>=9.2.0,<10",
  "glom>=24.11.0,<25",
  "jax[cuda12]>=0.5.3,<0.6",
  "jaxtyping>=0.3.0,<0.4",
  "lazy-loader",
  "liblaf-cherries>=0.0.9,<0.0.10",
  "liblaf-grapes>=0.1.13,<0.2",
  "liblaf-melon>=0.1.5,<0.2",
  "loguru",
  "numpy>=2.2.4,<3",
  "pyvista>=0.44.2,<0.45",
  "rich",
  "scipy>=1.15.2,<2",
]
description = "Add your description here"
dynamic = ["version"]
keywords = []
license = "MIT"
name = "liblaf-apple"
readme = "docs/README.md"
requires-python = ">=3.12"

[project.urls]
"Changelog" = "https://github.com/liblaf/apple/blob/main/CHANGELOG.md"
"Documentation" = "https://liblaf.github.io/apple/"
"Homepage" = "https://github.com/liblaf/apple"
"Issue Tracker" = "https://github.com/liblaf/apple/issues"
"Release Notes" = "https://github.com/liblaf/apple/releases"
"Source Code" = "https://github.com/liblaf/apple"

[tool.check-wheel-contents]
ignore = ["W002"]

[tool.coverage.run]
branch = true
source = ["src/"]

[tool.hatch.build.hooks.vcs]
version-file = "src/liblaf/apple/_version.py"

[tool.hatch.build.targets.sdist]
only-include = ["src/"]

[tool.hatch.build.targets.wheel]
packages = ["src/liblaf/"]

[tool.hatch.version]
source = "vcs"

[tool.pixi.dependencies]
pylops = ">=2.4.0,<3"
python = ">=3.12,<3.13"

[tool.pixi.environments]
default = { features = ["build", "dev", "docs", "test"] }

[tool.pixi.project]
channel-priority = "disabled"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
"liblaf-apple" = { editable = true, path = "." }

[tool.pixi.system-requirements]
cuda = "12"
libc = { family = "glibc", version = "2.41" }
linux = "6.13"

[tool.pytest.ini_options]
addopts = ["--showlocals", "--strict-config", "--strict-markers"]
junit_family = "legacy"
testpaths = ["benches/", "tests/"]
