#:schema https://json.schemastore.org/pyproject.json
# ref: <https://packaging.python.org/en/latest/specifications/pyproject-toml/>

[project]
name = "liblaf-apple"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [
  { name = "liblaf", email = "30631553+liblaf@users.noreply.github.com" },
]
keywords = []
classifiers = [
  # ref: <https://pypi.org/classifiers/>
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Typing :: Typed",
]
dependencies = [
  "beartype>=0.21,<0.22",
  "chex>=0.1,<0.2",
  "cytoolz>=1,<2",
  "einops>=0.8,<0.9",
  "equinox>=0.13,<0.14",
  "felupe>=9,<10",
  "ipctk>=1,<2",
  "jax[cuda12]>=0.7,<0.8",
  "jaxtyping>=0.3,<0.4",
  "lazy-loader>=0.4,<0.5",
  "liblaf-grapes>=2,<3",
  "liblaf-melon>=0.6,<0.7",
  "loguru>=0.7,<0.8",
  "matplotlib>=3.0,<4",
  "networkx>=3.0,<4",
  "numpy>=2.0,<3",
  "pyvista>=0.46,<0.47",
  "rich>=14,<15",
  "scipy>=1,<2",
  "wadler-lindig>=0.1,<0.2",
  "warp-lang==1.9.0.dev20250825",
]
dynamic = ["version"]

[project.urls]
"Changelog" = "https://github.com/liblaf/apple/blob/main/CHANGELOG.md"
"Documentation" = "https://liblaf.github.io/apple/"
"Homepage" = "https://github.com/liblaf/apple"
"Issue Tracker" = "https://github.com/liblaf/apple/issues"
"Release Notes" = "https://github.com/liblaf/apple/releases"
"Source Code" = "https://github.com/liblaf/apple"

[dependency-groups]
build = ["check-wheel-contents>=0.6,<0.7", "hatch>=1,<2", "twine>=6,<7"]
dev = [
  "icecream>=2,<3",
  "liblaf-cherries>=0.4,<0.5",
  "marimo[recommended]>=0.15,<0.16",
  "sympy>=1,<2",
  "viztracer>=1,<2",
]
docs = ["liblaf-mkdocs-preset>=0.2,<0.3", "mkdocs>=1,<2"]
test = [
  "hypothesis>=6,<7",
  "pytest-codspeed>=4,<5",
  "pytest-cov>=6,<7",
  "pytest-randomly>=3,<4",
  "pytest-xdist>=3,<4",
  "pytest>=8,<9",
]

[build-system]
requires = ["hatch-vcs", "hatchling"]
build-backend = "hatchling.build"

[tool.check-wheel-contents]
ignore = ["W002"]

[tool.coverage.run]
branch = true
source = ["src/"]

[tool.hatch.build.hooks.vcs]
version-file = "src/liblaf/apple/_version.py"

[tool.hatch.build.targets.sdist]
only-include = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/liblaf"]

[tool.hatch.version]
source = "vcs"

[tool.pyright]
exclude = ["**/.*", "**/__pycache__", "**/marimo", "**/node_modules"]
extends = ".config/linters/pyrightconfig.json"

[tool.pytest.ini_options]
addopts = [
  "--doctest-modules",
  "--hypothesis-show-statistics",
  "--showlocals",
  "--strict-config",
  "--strict-markers",
]
testpaths = ["benches", "src", "tests"]

[tool.ruff]
extend = ".config/linters/.ruff.toml"
extend-exclude = ["marimo"]

[tool.ruff.lint]
ignore = ["F722", "N802", "N803", "N806", "N815", "PLR0913", "RUF002"]

[tool.uv]
default-groups = "all"

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com/"

[tool.uv.sources]
warp-lang.index = "nvidia"
