#:schema https://json.schemastore.org/pyproject.json
# https://packaging.python.org/en/latest/specifications/pyproject-toml/

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = ["icecream>=2.1.4,<3", "pytetwild>=0.1.dev1,<0.2", "typer>=0.15.1,<0.16"]
docs = [
  "mdx-truly-sane-lists>=1.3,<2",
  "mkdocs-autorefs>=1.3.0,<2",
  "mkdocs-gen-files>=0.5.0,<0.6",
  "mkdocs-git-committers-plugin-2>=2.5.0,<3",
  "mkdocs-git-revision-date-localized-plugin>=1.3.0,<2",
  "mkdocs-literate-nav>=0.6.1,<0.7",
  "mkdocs-material[imaging]>=9.6.3,<10",
  "mkdocs-section-index>=0.3.9,<0.4",
  "mkdocs>=1.6.1,<2",
  "mkdocstrings[python]>=0.28.0,<0.29",
  "pymdown-extensions>=10.14.3,<11",
]

[project]
authors = [
  { email = "30631553+liblaf@users.noreply.github.com", name = "liblaf" },
]
classifiers = []
dependencies = [
  "autoregistry>=1.1.2,<2",
  "felupe>=9.1.0,<10",
  "jaxtyping>=0.2.37,<0.3",
  "lazy-loader>=0.4,<0.5",
  "liblaf-cherries>=0.0.2,<0.0.3",
  "liblaf-grapes>=0.0.3,<0.0.4",
  "liblaf-melon>=0.1.0,<0.2",
  "numpy",
  "pytetwild",
  "pyvista>=0.44.2,<0.45",
  "scipy",
]
description = "Add your description here"
keywords = []
license = "MIT"
name = "liblaf-apple"
readme = "docs/README.md"
requires-python = ">=3.12"
version = "0.0.0"

[project.urls]
"Changelog" = "https://github.com/liblaf/apple/blob/main/CHANGELOG.md"
"Homepage" = "https://github.com/liblaf/apple"
"Issue Tracker" = "https://github.com/liblaf/apple/issues"
"Release Notes" = "https://github.com/liblaf/apple/releases"
"Source Code" = "https://github.com/liblaf/apple"

[tool.check-wheel-contents]
ignore = ["W002"]

[tool.hatch.build.targets.wheel]
packages = ["src/liblaf"]

[tool.pixi.dependencies]
jax = ">=0.4.35,<0.5"
jaxlib = { build = "*cuda*", version = ">=0.4.35,<0.5" }
python = ">=3.12,<3.13"

[tool.pixi.environments]
default = ["dev", "docs"]

[tool.pixi.project]
channel-priority = "disabled"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
"liblaf-apple" = { editable = true, path = "." }

[tool.pixi.system-requirements]
cuda = "12"
libc = { family = "glibc", version = "2.40" }
linux = "6.6"
