#:schema https://json.schemastore.org/pyproject.json
# ref: <https://packaging.python.org/en/latest/specifications/pyproject-toml/>

[project]
name = "liblaf-apple"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [
  { name = "liblaf", email = "30631553+liblaf@users.noreply.github.com" },
]
keywords = []
classifiers = [
  # common classifiers
  # ref: <https://pypi.org/classifiers/>
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Typing :: Typed",
]
dependencies = [
  "beartype>=0.21.0,<0.22",
  "chex>=0.1.0,<0.2",
  "cytoolz>=1.0.0,<2",
  "einops>=0.8.0,<0.9",
  "equinox>=0.13.0,<0.14",
  "felupe>=9.0.0,<10",
  "flax>=0.10.0,<0.11",
  "h5py>=3.14.0",
  "ipctk>=1.0.0,<2",
  "jax[cuda12]>=0.6.0,<0.7",
  "jaxtyping>=0.3.0,<0.4",
  "lazy-loader>=0.4.0,<0.5",
  "liblaf-grapes>=1.0.0,<2",
  "liblaf-melon>=0.5.0,<0.6",
  "loguru>=0.7.0,<0.8",
  "matplotlib>=3.0.0,<4",
  "networkx>=3.0.0,<4",
  "numpy>=2.0.0,<3",
  "plum-dispatch>=2.0.0,<3",
  "pyvista>=0.45.0,<0.46",
  "rich>=14.0.0,<15",
  "scipy>=1.0.0,<2",
  "wadler-lindig>=0.1.0,<0.2",
  "warp-lang>=1.0.0,<2",
]
dynamic = ["version"]

[project.urls]
"Changelog" = "https://github.com/liblaf/apple/blob/main/CHANGELOG.md"
"Documentation" = "https://liblaf.github.io/apple/"
"Homepage" = "https://github.com/liblaf/apple"
"Issue Tracker" = "https://github.com/liblaf/apple/issues"
"Release Notes" = "https://github.com/liblaf/apple/releases"
"Source Code" = "https://github.com/liblaf/apple"

[dependency-groups]
build = ["check-wheel-contents", "hatch", "twine"]
dev = [
  "icecream",
  "imageio[ffmpeg]",
  "liblaf-cherries",
  "marimo[recommended]",
  "mypy>=1.17.0",
  "sympy",
  "viztracer",
]
docs = [
  "docstring-inheritance",
  "griffe-fieldz",
  "griffe-generics",
  "griffe-inherited-docstrings",
  "griffe-modernized-annotations",
  "griffe-pydantic",
  "griffe-warnings-deprecated",
  "mdx-truly-sane-lists",
  "mkdocs",
  "mkdocs-api-autonav",
  "mkdocs-autorefs",
  "mkdocs-git-committers-plugin-2",
  "mkdocs-git-revision-date-localized-plugin",
  "mkdocs-include-markdown-plugin",
  "mkdocs-material[imaging]",
  "mkdocs-section-index",
  "mkdocstrings",
  "mkdocstrings-python",
  "pymdown-extensions",
  "ruff",
]
test = ["hypothesis", "pytest", "pytest-codspeed", "pytest-cov", "pytest-xdist"]

[build-system]
requires = ["hatch-vcs", "hatchling"]
build-backend = "hatchling.build"

[tool.check-wheel-contents]
ignore = ["W002"]

[tool.coverage.run]
branch = true
source = ["src/"]

[tool.hatch.build.hooks.vcs]
version-file = "src/liblaf/apple/_version.py"

[tool.hatch.build.targets.sdist]
only-include = ["src/"]

[tool.hatch.build.targets.wheel]
packages = ["src/liblaf/"]

[tool.hatch.version]
source = "vcs"

[tool.pytest.ini_options]
addopts = [
  "--hypothesis-show-statistics",
  "--showlocals",
  "--strict-config",
  "--strict-markers",
]
testpaths = ["benches/", "tests/"]

[tool.uv]
default-groups = "all"
