#:schema https://json.schemastore.org/pyproject.json
# ref: <https://packaging.python.org/en/latest/specifications/pyproject-toml/>

[build-system]
build-backend = "hatchling.build"
requires = ["hatch-vcs", "hatchling"]

[dependency-groups]
build = ["check-wheel-contents", "hatch", "twine"]
dev = ["icecream", "liblaf-cherries", "marimo[recommended]", "sympy"]
docs = [
  "docstring-inheritance",
  "griffe-fieldz",
  "griffe-generics",
  "griffe-inherited-docstrings",
  "griffe-modernized-annotations",
  "griffe-pydantic",
  "griffe-warnings-deprecated",
  "mdx-truly-sane-lists",
  "mkdocs",
  "mkdocs-api-autonav",
  "mkdocs-autorefs",
  "mkdocs-git-committers-plugin-2",
  "mkdocs-git-revision-date-localized-plugin",
  "mkdocs-include-markdown-plugin",
  "mkdocs-material[imaging]",
  "mkdocs-section-index",
  "mkdocstrings",
  "mkdocstrings-python",
  "pymdown-extensions",
  "ruff",
]
test = [
  "pytest",
  "pytest-benchmark",
  "pytest-codspeed",
  "pytest-cov",
  "pytest-xdist",
]

[project]
authors = [
  { email = "30631553+liblaf@users.noreply.github.com", name = "liblaf" },
]
classifiers = [
  # common classifiers
  # ref: <https://pypi.org/classifiers/>
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "License :: OSI Approved",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python",
  "Typing :: Typed",
]
dependencies = [
  "beartype>=0.21.0,<0.22",
  "chex>=0.1.89,<0.2",
  "einops>=0.8.1,<0.9",
  "equinox>=0.12.2,<0.13",
  "felupe>=9.2.0,<10",
  "flax>=0.10.6,<0.11",
  "ipctk>=1.3.1,<2",
  "jaxtyping>=0.3.2,<0.4",
  "lazy-loader>=0.4,<0.5",
  "liblaf-grapes>=0.2.2,<0.3",
  "liblaf-melon>=0.3.0,<0.4",
  "loguru>=0.7.3,<0.8",
  "networkx>=3.5,<4",
  "numpy",
  "pyvista>=0.45.2,<0.46",
  "rich>=14.0.0,<15",
  "scipy",
  "tinyobjloader",
  "wadler-lindig",
]
description = "Add your description here"
dynamic = ["version"]
keywords = []
license = "MIT"
name = "liblaf-apple"
readme = "README.md"
requires-python = ">=3.12"

[project.urls]
"Changelog" = "https://github.com/liblaf/apple/blob/main/CHANGELOG.md"
"Documentation" = "https://liblaf.github.io/apple/"
"Homepage" = "https://github.com/liblaf/apple"
"Issue Tracker" = "https://github.com/liblaf/apple/issues"
"Release Notes" = "https://github.com/liblaf/apple/releases"
"Source Code" = "https://github.com/liblaf/apple"

[tool.check-wheel-contents]
ignore = ["W002"]

[tool.coverage.run]
branch = true
source = ["src/"]

[tool.hatch.build.hooks.vcs]
version-file = "src/liblaf/apple/_version.py"

[tool.hatch.build.targets.sdist]
only-include = ["src/"]

[tool.hatch.build.targets.wheel]
packages = ["src/liblaf/"]

[tool.hatch.version]
source = "vcs"

[tool.pixi.dependencies]
jax = ">=0.6.0,<0.7"
jaxlib = { build = "*cuda*", version = ">=0.6.0,<0.7" }
python = "3.12.*"
warp-lang = { build = "*cuda*", version = ">=1.7.1,<2" }

[tool.pixi.environments]
default = { features = ["build", "dev", "docs", "test"] }

[tool.pixi.project]
channel-priority = "disabled"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
"liblaf-apple" = { editable = true, path = "." }

[tool.pixi.system-requirements]
cuda = "12"
libc = { family = "glibc", version = "2.41" }
linux = "6.13"

[tool.pytest.ini_options]
addopts = ["--showlocals", "--strict-config", "--strict-markers"]
testpaths = ["benches/", "tests/"]
