import warp as wp
from warp.fem.linalg import array_axpy as array_axpy, symmetric_eigenvalues_qr as symmetric_eigenvalues_qr
from warp.sparse import BsrMatrix as BsrMatrix, bsr_assign as bsr_assign, bsr_axpy as bsr_axpy, bsr_copy as bsr_copy, bsr_mm as bsr_mm, bsr_mv as bsr_mv
from warp.types import type_is_matrix as type_is_matrix, type_size as type_size

def normalize_dirichlet_projector(projector_matrix: BsrMatrix, fixed_value: wp.array | None = None): ...
def project_system_rhs(system_matrix: BsrMatrix, system_rhs: wp.array, projector_matrix: BsrMatrix, fixed_value: wp.array | None = None): ...
def project_system_matrix(system_matrix: BsrMatrix, projector_matrix: BsrMatrix): ...
def project_linear_system(system_matrix: BsrMatrix, system_rhs: wp.array, projector_matrix: BsrMatrix, fixed_value: wp.array | None = None, normalize_projector: bool = True): ...
