import warp as wp
from typing import Any

@wp.func
def symmetric_part(x: Any): ...
@wp.func
def householder_qr_decomposition(A: Any): ...
@wp.func
def householder_make_hessenberg(A: Any): ...
@wp.func
def solve_triangular(R: Any, b: Any): ...
@wp.func
def inverse_qr(A: Any): ...
@wp.func
def tridiagonal_symmetric_eigenvalues_qr(D: Any, L: Any, Q: Any, tol: Any): ...
@wp.func
def symmetric_eigenvalues_qr(A: Any, tol: Any): ...
def array_axpy(x: wp.array, y: wp.array, alpha: float = 1.0, beta: float = 1.0): ...
