import numpy as np
import warp as wp

def bourke_color_map(low, high, v): ...
def tab10_color_map(i): ...
@wp.kernel
def solidify_mesh_kernel(indices: None, vertices: None, thickness: None, out_vertices: None, out_indices: None): ...
def solidify_mesh(faces: np.ndarray, vertices: np.ndarray, thickness: list | float): ...
