from collections.abc import Callable, Mapping
from typing import Any

type _MappingFactory = Callable[[], Mapping]

def assoc(
    d: Mapping, key: Any, value: Any, factory: _MappingFactory = ...
) -> Mapping: ...
def dissoc(d: Mapping, key: Any, factory: _MappingFactory = ...) -> Mapping: ...
def merge(*dicts: Mapping, factory: _MappingFactory = ...) -> Mapping: ...
def valmap(func: Callable, d: Mapping, factory: _MappingFactory = ...) -> Mapping: ...
