from .field import DiscreteField as DiscreteField, FieldLike as FieldLike, GeometryField as GeometryField, ImplicitField as ImplicitField, NonconformingField as NonconformingField, SpaceField as SpaceField, UniformField as UniformField
from .nodal_field import NodalField as NodalField
from .restriction import FieldRestriction as FieldRestriction
from .virtual import LocalTestField as LocalTestField, LocalTrialField as LocalTrialField, TestField as TestField, TrialField as TrialField
from warp.fem.domain import Cells as Cells, GeometryDomain as GeometryDomain
from warp.fem.space import FunctionSpace as FunctionSpace, SpacePartition as SpacePartition, SpaceRestriction as SpaceRestriction, make_space_partition as make_space_partition, make_space_restriction as make_space_restriction

def make_restriction(field: DiscreteField, space_restriction: SpaceRestriction | None = None, domain: GeometryDomain | None = None, device=None) -> FieldRestriction: ...
def make_test(space: FunctionSpace, space_restriction: SpaceRestriction | None = None, space_partition: SpacePartition | None = None, domain: GeometryDomain | None = None, device=None) -> TestField: ...
def make_trial(space: FunctionSpace, space_restriction: SpaceRestriction | None = None, space_partition: SpacePartition | None = None, domain: GeometryDomain | None = None) -> TrialField: ...
def make_discrete_field(space: FunctionSpace, space_partition: SpacePartition | None = None) -> DiscreteField: ...
