DIRICHLET_MASK = "DirichletMask"
DIRICHLET_VALUE = "DirichletValue"
POINT_ID = "PointId"

ACTIVATION = "Activation"
LAMBDA = "lambda"
MASS = "Mass"
MU = "mu"
MUSCLE_FRACTION = "MuscleFraction"
STIFFNESS = "Stiffness"
