import warp as wp
from _typeshed import Incomplete

@wp.kernel
def adam_step_kernel_vec3(g: None, m: None, v: None, lr: float, beta1: float, beta2: float, t: float, eps: float, params: None): ...
@wp.kernel
def adam_step_kernel_float(g: None, m: None, v: None, lr: float, beta1: float, beta2: float, t: float, eps: float, params: None): ...
@wp.kernel
def adam_step_kernel_half(g: None, m: None, v: None, lr: float, beta1: float, beta2: float, t: float, eps: float, params: None): ...

class Adam:
    m: Incomplete
    v: Incomplete
    lr: Incomplete
    beta1: Incomplete
    beta2: Incomplete
    eps: Incomplete
    t: int
    def __init__(self, params=None, lr: float = 0.001, betas=(0.9, 0.999), eps: float = 1e-08) -> None: ...
    params: Incomplete
    def set_params(self, params) -> None: ...
    def reset_internal_state(self) -> None: ...
    def step(self, grad) -> None: ...
    @staticmethod
    def step_detail(g, m, v, lr, beta1, beta2, t, eps, params) -> None: ...
