from warp.utils import ScopedTimer as ScopedTimer

verbose_cmd: bool

def machine_architecture() -> str: ...
def run_cmd(cmd): ...
def set_msvc_env(msvc_path, sdk_path): ...
def find_host_compiler(): ...
def get_cuda_toolkit_version(cuda_home): ...
def quote(path): ...
def add_llvm_bin_to_path(args): ...
def build_dll_for_arch(args, dll_path, cpp_paths, cu_path, arch, libs: list[str] | None = None, mode=None): ...
def build_dll(args, dll_path, cpp_paths, cu_path, libs=None) -> None: ...
