import warp

def device_to_jax(warp_device: warp.context.Devicelike): ...
def device_from_jax(jax_device) -> warp.context.Device: ...
def get_jax_device(): ...
def dtype_to_jax(warp_dtype): ...
def dtype_from_jax(jax_dtype): ...
def to_jax(warp_array): ...
def from_jax(jax_array, dtype=None) -> warp.array: ...
