"""
Python bindings for the `Fast Interval Library (Filib) <https://github.com/zfergus/filib>`_ by Werner Hofschuster and Walter Kraemer.
"""

from __future__ import annotations
import typing

__all__: list[str] = [
    "Interval",
    "acos",
    "acosh",
    "acot",
    "acoth",
    "asin",
    "asinh",
    "atan",
    "atanh",
    "cos",
    "cosh",
    "cot",
    "coth",
    "disjoint",
    "erf",
    "erfc",
    "exp",
    "exp10",
    "exp2",
    "expm1",
    "log",
    "log10",
    "log1p",
    "log2",
    "max",
    "min",
    "sin",
    "sinh",
    "sqr",
    "sqrt",
    "tan",
    "tanh",
]

class Interval:
    __hash__: typing.ClassVar[None] = None
    @typing.overload
    def __add__(self, arg0: Interval) -> Interval: ...
    @typing.overload
    def __add__(self, arg0: typing.SupportsFloat) -> Interval: ...
    def __and__(self, arg0: Interval) -> Interval: ...
    @typing.overload
    def __contains__(self, arg0: typing.SupportsFloat) -> bool: ...
    @typing.overload
    def __contains__(self, arg0: Interval) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Interval) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.SupportsFloat) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.SupportsFloat) -> bool: ...
    @typing.overload
    def __ge__(self, arg0: typing.SupportsFloat) -> bool: ...
    @typing.overload
    def __ge__(self, arg0: Interval) -> bool: ...
    @typing.overload
    def __ge__(self, arg0: typing.SupportsFloat) -> bool: ...
    @typing.overload
    def __gt__(self, arg0: typing.SupportsFloat) -> bool: ...
    @typing.overload
    def __gt__(self, arg0: Interval) -> bool: ...
    @typing.overload
    def __gt__(self, arg0: typing.SupportsFloat) -> bool: ...
    @typing.overload
    def __iadd__(self, arg0: Interval) -> Interval: ...
    @typing.overload
    def __iadd__(self, arg0: typing.SupportsFloat) -> Interval: ...
    @typing.overload
    def __imul__(self, arg0: Interval) -> Interval: ...
    @typing.overload
    def __imul__(self, arg0: typing.SupportsFloat) -> Interval: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, x: typing.SupportsFloat) -> None: ...
    @typing.overload
    def __init__(self, x: typing.SupportsFloat, y: typing.SupportsFloat) -> None: ...
    @typing.overload
    def __isub__(self, arg0: Interval) -> Interval: ...
    @typing.overload
    def __isub__(self, arg0: typing.SupportsFloat) -> Interval: ...
    @typing.overload
    def __itruediv__(self, arg0: Interval) -> Interval: ...
    @typing.overload
    def __itruediv__(self, arg0: typing.SupportsFloat) -> Interval: ...
    @typing.overload
    def __le__(self, arg0: Interval) -> bool: ...
    @typing.overload
    def __le__(self, arg0: typing.SupportsFloat) -> bool: ...
    @typing.overload
    def __le__(self, arg0: typing.SupportsFloat) -> bool: ...
    @typing.overload
    def __lt__(self, arg0: Interval) -> bool: ...
    @typing.overload
    def __lt__(self, arg0: typing.SupportsFloat) -> bool: ...
    @typing.overload
    def __lt__(self, arg0: typing.SupportsFloat) -> bool: ...
    @typing.overload
    def __mul__(self, arg0: Interval) -> Interval: ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat) -> Interval: ...
    @typing.overload
    def __ne__(self, arg0: Interval) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: typing.SupportsFloat) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: typing.SupportsFloat) -> bool: ...
    def __neg__(self) -> Interval: ...
    def __or__(self, arg0: Interval) -> Interval: ...
    def __pos__(self) -> Interval: ...
    def __pow__(self, arg0: typing.SupportsFloat) -> Interval: ...
    def __radd__(self, arg0: typing.SupportsFloat) -> Interval: ...
    def __repr__(self) -> str: ...
    def __rmul__(self, arg0: typing.SupportsFloat) -> Interval: ...
    def __rpow__(self, arg0: typing.SupportsFloat) -> Interval: ...
    def __rsub__(self, arg0: typing.SupportsFloat) -> Interval: ...
    def __rtruediv__(self, arg0: typing.SupportsFloat) -> Interval: ...
    def __str__(self) -> str: ...
    @typing.overload
    def __sub__(self, arg0: Interval) -> Interval: ...
    @typing.overload
    def __sub__(self, arg0: typing.SupportsFloat) -> Interval: ...
    @typing.overload
    def __truediv__(self, arg0: Interval) -> Interval: ...
    @typing.overload
    def __truediv__(self, arg0: typing.SupportsFloat) -> Interval: ...
    def acos(self) -> Interval: ...
    def acosh(self) -> Interval: ...
    def acot(self) -> Interval: ...
    def acoth(self) -> Interval: ...
    def arccos(self) -> Interval: ...
    def arccosh(self) -> Interval: ...
    def arccot(self) -> Interval: ...
    def arccoth(self) -> Interval: ...
    def arcsin(self) -> Interval: ...
    def arcsinh(self) -> Interval: ...
    def arctan(self) -> Interval: ...
    def arctanh(self) -> Interval: ...
    def asin(self) -> Interval: ...
    def asinh(self) -> Interval: ...
    def atan(self) -> Interval: ...
    def atanh(self) -> Interval: ...
    def blow(self, arg0: typing.SupportsFloat) -> Interval: ...
    def cos(self) -> Interval: ...
    def cosh(self) -> Interval: ...
    def cot(self) -> Interval: ...
    def coth(self) -> Interval: ...
    def diam(self) -> float: ...
    def drel(self) -> float: ...
    def empty(self) -> bool: ...
    def erf(self) -> Interval: ...
    def erfc(self) -> Interval: ...
    def exp(self) -> Interval: ...
    def exp10(self) -> Interval: ...
    def exp2(self) -> Interval: ...
    def expm1(self) -> Interval: ...
    def log(self) -> Interval: ...
    def log10(self) -> Interval: ...
    def log1p(self) -> Interval: ...
    def log2(self) -> Interval: ...
    def mid(self) -> float: ...
    def sin(self) -> Interval: ...
    def sinh(self) -> Interval: ...
    def sqr(self) -> Interval: ...
    def sqrt(self) -> Interval: ...
    def tan(self) -> Interval: ...
    def tanh(self) -> Interval: ...
    @property
    def INF(self) -> float: ...
    @INF.setter
    def INF(self, arg0: typing.SupportsFloat) -> None: ...
    @property
    def SUP(self) -> float: ...
    @SUP.setter
    def SUP(self, arg0: typing.SupportsFloat) -> None: ...

def acos(arg0: Interval) -> Interval: ...
def acosh(arg0: Interval) -> Interval: ...
def acot(arg0: Interval) -> Interval: ...
def acoth(arg0: Interval) -> Interval: ...
def asin(arg0: Interval) -> Interval: ...
def asinh(arg0: Interval) -> Interval: ...
def atan(arg0: Interval) -> Interval: ...
def atanh(arg0: Interval) -> Interval: ...
def cos(arg0: Interval) -> Interval: ...
def cosh(arg0: Interval) -> Interval: ...
def cot(arg0: Interval) -> Interval: ...
def coth(arg0: Interval) -> Interval: ...
def disjoint(arg0: Interval, arg1: Interval) -> bool: ...
def erf(arg0: Interval) -> Interval: ...
def erfc(arg0: Interval) -> Interval: ...
def exp(arg0: Interval) -> Interval: ...
def exp10(arg0: Interval) -> Interval: ...
def exp2(arg0: Interval) -> Interval: ...
def expm1(arg0: Interval) -> Interval: ...
def log(arg0: Interval) -> Interval: ...
def log10(arg0: Interval) -> Interval: ...
def log1p(arg0: Interval) -> Interval: ...
def log2(arg0: Interval) -> Interval: ...
@typing.overload
def max(arg0: Interval, arg1: Interval) -> Interval: ...
@typing.overload
def max(arg0: Interval, arg1: typing.SupportsFloat) -> Interval: ...
@typing.overload
def max(arg0: typing.SupportsFloat, arg1: Interval) -> Interval: ...
@typing.overload
def min(arg0: Interval, arg1: Interval) -> Interval: ...
@typing.overload
def min(arg0: Interval, arg1: typing.SupportsFloat) -> Interval: ...
@typing.overload
def min(arg0: typing.SupportsFloat, arg1: Interval) -> Interval: ...
def sin(arg0: Interval) -> Interval: ...
def sinh(arg0: Interval) -> Interval: ...
def sqr(arg0: Interval) -> Interval: ...
def sqrt(arg0: Interval) -> Interval: ...
def tan(arg0: Interval) -> Interval: ...
def tanh(arg0: Interval) -> Interval: ...
