import warp as wp
from enum import Enum

class ColoringAlgorithm(Enum):
    MCS = 0
    GREEDY = 1

@wp.kernel
def construct_trimesh_graph_edges_kernel(trimesh_edge_indices: None, add_bending: bool, graph_edge_indices: None, graph_num_edges: None): ...
@wp.kernel
def validate_graph_coloring(edge_indices: None, colors: None): ...
@wp.kernel
def count_color_group_size(colors: None, group_sizes: None): ...
@wp.kernel
def fill_color_groups(colors: None, group_fill_count: None, group_offsets: None, color_groups_flatten: None): ...
def convert_to_color_groups(num_colors, particle_colors, return_wp_array: bool = False, device: str = 'cpu'): ...
def construct_trimesh_graph_edges(trimesh_edge_indices, return_wp_array: bool = False): ...
def color_trimesh(num_nodes, trimesh_edge_indices, include_bending_energy, balance_colors: bool = True, target_max_min_color_ratio: float = 1.1, algorithm: ColoringAlgorithm = ...): ...
def color_graph(num_nodes, graph_edge_indices, balance_colors: bool = True, target_max_min_color_ratio: float = 1.1, algorithm: ColoringAlgorithm = ...): ...
def combine_independent_particle_coloring(color_groups_1, color_groups_2): ...
