import warp as wp
from .model import Control as Control, Model as Model, PARTICLE_FLAG_ACTIVE as PARTICLE_FLAG_ACTIVE, State as State

@wp.kernel
def integrate_particles(x: None, v: None, f: None, w: None, particle_flags: None, gravity: wp.vec3, dt: float, v_max: float, x_new: None, v_new: None): ...
@wp.func
def integrate_rigid_body(q: wp.transform, qd: wp.spatial_vector, f: wp.spatial_vector, com: wp.vec3, inertia: wp.mat33, inv_mass: float, inv_inertia: wp.mat33, gravity: wp.vec3, angular_damping: float, dt: float): ...
@wp.kernel
def integrate_bodies(body_q: None, body_qd: None, body_f: None, body_com: None, m: None, I: None, inv_m: None, inv_I: None, gravity: wp.vec3, angular_damping: float, dt: float, body_q_new: None, body_qd_new: None): ...

class Integrator:
    def integrate_bodies(self, model: Model, state_in: State, state_out: State, dt: float, angular_damping: float = 0.0): ...
    def integrate_particles(self, model: Model, state_in: State, state_out: State, dt: float): ...
    def simulate(self, model: Model, state_in: State, state_out: State, dt: float, control: Control = None): ...
