import warp as wp
from .model import PARTICLE_FLAG_ACTIVE as PARTICLE_FLAG_ACTIVE

@wp.func
def particle_force(n: wp.vec3, v: wp.vec3, c: float, k_n: float, k_d: float, k_f: float, k_mu: float): ...
@wp.kernel
def eval_particle_forces_kernel(grid: wp.uint64, particle_x: None, particle_v: None, particle_radius: None, particle_flags: None, k_contact: float, k_damp: float, k_friction: float, k_mu: float, k_cohesion: float, max_radius: float, particle_f: None): ...
def eval_particle_forces(model, state, forces) -> None: ...
