name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - if: hashFiles('pixi.lock') != ''
        name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0
        with:
          run-install: true
          activate-environment: true
          locked: false
      - if: hashFiles('uv.lock') != ''
        name: Setup uv
        uses: astral-sh/setup-uv@v5
      - name: Test
        run: pytest --junit-xml="junit.xml" --cov --cov-report="xml" --cov-branch --numprocesses="auto"
      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
      - if: !cancelled()
        name: Upload Test Results
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
